// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDBTaEcya9P2YR-VKnMUbumGybrEnvVxg',
    appId: '1:206967793471:web:21f662b2e24e040da8d58a',
    messagingSenderId: '206967793471',
    projectId: 'pideqr-8fbfc',
    authDomain: 'pideqr-8fbfc.firebaseapp.com',
    storageBucket: 'pideqr-8fbfc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBidU0lKu29OL3TgxvLRCru8h5Twxsji6E',
    appId: '1:206967793471:android:c4836f01943da972a8d58a',
    messagingSenderId: '206967793471',
    projectId: 'pideqr-8fbfc',
    storageBucket: 'pideqr-8fbfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpkeExg4bI5Z1UtzE1sdzvANHWnnjM9DI',
    appId: '1:206967793471:ios:905d472e0389b72aa8d58a',
    messagingSenderId: '206967793471',
    projectId: 'pideqr-8fbfc',
    storageBucket: 'pideqr-8fbfc.firebasestorage.app',
    iosBundleId: 'com.example.pideqr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpkeExg4bI5Z1UtzE1sdzvANHWnnjM9DI',
    appId: '1:206967793471:ios:905d472e0389b72aa8d58a',
    messagingSenderId: '206967793471',
    projectId: 'pideqr-8fbfc',
    storageBucket: 'pideqr-8fbfc.firebasestorage.app',
    iosBundleId: 'com.example.pideqr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDBTaEcya9P2YR-VKnMUbumGybrEnvVxg',
    appId: '1:206967793471:web:a24ee7b888a88cf7a8d58a',
    messagingSenderId: '206967793471',
    projectId: 'pideqr-8fbfc',
    authDomain: 'pideqr-8fbfc.firebaseapp.com',
    storageBucket: 'pideqr-8fbfc.firebasestorage.app',
  );

}